[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# 依存するライブラリクレートを指定
# ライブラリクレートの登録場所 https://crates.io/
[dependencies]
rand = "0.8.3" # ^0.8.3 の略式記法
